plugins {
    id 'fabric-loom' version '1.10-SNAPSHOT'
    id 'maven-publish'
}

apply plugin: 'java'
apply plugin: 'idea'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

version = project.mod_version
group = project.maven_group
base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name 'Xander Maven'
        url 'https://maven.isxander.dev/releases'
    }

    maven {
        name 'terraformersmc Maven'
        url "https://maven.terraformersmc.com"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation 'com.google.code.findbugs:jsr305:3.0.2'
}

loom {
    // accessWidenerPath = file("src/main/resources/${project.archives_base_name}.accesswidener")

    runs {
        server {
            runDir "run/server"
        }
        client {
            runDir "run/client"
        }
    }
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand ([
                "archives_base_name" : project.archives_base_name,
                "mod_version"        : project.mod_version,
                "mod_name"           : project.mod_name,
                "mod_description"    : project.mod_description,
                "repo_url"           : project.repo_url,
                "license"            : project.license
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 17
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}